[package]
name = "lean-squares-in-fibonacci"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
lean-squares-in-fibonacci = {git = "https://github.com/kbuzzard/lean-squares-in-fibonacci", rev = "beea5fd65e8ae4a7b11eaa1fdd768f5e1d05222b"}
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "36dd78ee328b93f7bbf36b001807060efb562822"}
